Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "master.local"
    subconfig.vm.network "private_network", ip: "192.168.50.10"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node1"
    subconfig.vm.network "private_network", ip: "192.168.50.11"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node2"
    subconfig.vm.network "private_network", ip: "192.168.50.12"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end
end